Models/Tarea.cs
using EspacioViewModels;
namespace EspacioModels;

public enum EstadoTarea {
    Idea = 0,
    Hacer = 1,
    Haciendo = 2,
    Revisar = 3,
    Terminada = 4
}
public class Tarea {
    private int id;
    private int id_tablero;
    private string nombre;
    private string descripcion;
    private string color;
    private EstadoTarea estado;
    private int id_usuario_asignado;

    public int Id { get => id; set => id = value; }
    public int Id_tablero { get => id_tablero; set => id_tablero = value; }
    public string Nombre { get => nombre; set => nombre = value; }
    public string Descripcion { get => descripcion; set => descripcion = value; }
    public string Color { get => color; set => color = value; }
    public EstadoTarea Estado { get => estado; set => estado = value; }
    public int Id_usuario_asignado { get => id_usuario_asignado; set => id_usuario_asignado = value; }

    public Tarea(){ }

    public Tarea(TareaCrearView tarea){
        id_tablero = tarea.Id_tablero;
        nombre = tarea.Nombre;
        descripcion = tarea.Descripcion;
        color = tarea.Color;
        estado = tarea.Estado;
        id_usuario_asignado = tarea.Id_usuario_asignado;
    }
    public Tarea(TareaModificarView tarea){
        id = tarea.Id;
        id_tablero = tarea.Id_tablero;
        nombre = tarea.Nombre;
        descripcion = tarea.Descripcion;
        color = tarea.Color;
        estado = tarea.Estado;
        id_usuario_asignado = tarea.Id_usuario_asignado;
    }
    
}

ViewModels/TareaView.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using EspacioModels;

namespace EspacioViewModels
{
    public class TareaView
    {
        [Display(Name = "Id")]
        public int Id {get;set;}

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Id tablero")] 
        public int Id_tablero {get;set;} 

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Nombre")] 
        [StringLength(80)]
        public string Nombre {get;set;}  

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Estado")] 
        public EstadoTarea Estado {get;set;}        
        
        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Descripcion")]
        [StringLength(100)]
        public string? Descripcion {get;set;}

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Color")]
        public string? Color {get;set;}

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "ID Usuario")]
        public int Id_usuario_asignado {get;set;} 

        private string? usuario;
        public string? Usuario {get; set;}
        
        private string? tablero;
        public string? Tablero {get; set;}

        public TareaView() { }

        public TareaView(Tarea tarea, Usuario usu, Tablero tab)
        {
            Id = tarea.Id;
            Id_tablero = tarea.Id_tablero;
            Nombre = tarea.Nombre;
            Estado = tarea.Estado;
            Descripcion = tarea.Descripcion;
            Color = tarea.Color;
            Id_usuario_asignado = usu.Id;
            Usuario = usu.Nombre_de_usuario;
            Tablero = tab.Nombre;
        }
    }
}

Controllers/TareaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_vaninaze.Models;

using kanbanRepository;
using EspacioModels;
using EspacioViewModels;
namespace tl2_tp10_2023_vaninaze.Controllers;

public class TareaController : Controller
{
    private readonly ILogger<TareaController> _logger;
    private ITareaRepository tareaRepo;
    private IUsuarioRepository usuarioRepo;
    private ITableroRepository tableroRepo;

    public TareaController(ILogger<TareaController> logger, ITareaRepository _tareaRepo, IUsuarioRepository _usuarioRepo, ITableroRepository _tableroRepo)
    {
        _logger = logger;
        tareaRepo = _tareaRepo;
        usuarioRepo = _usuarioRepo;
        tableroRepo = _tableroRepo;
    }

    [HttpGet]
    public IActionResult Index() //Listar tareas
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        }       
        try {
            int id = HttpContext.Session.GetInt32("id") ?? -1;
            List<Tarea> tareas = tareaRepo.GetAll();
            TareaListadoView tareasView = new TareaListadoView(tareas, usuarioRepo.GetAll(), tableroRepo.GetAll(), id);
            return View(tareasView);
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }

    [HttpGet]
    public IActionResult CrearTarea()
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            int id = HttpContext.Session.GetInt32("id") ?? -1;
            if(isAdmin()){
                return View("CrearTareaAdmin", new TareaCrearView(new Tarea(), id, usuarioRepo.GetAll(), tableroRepo.GetAll()));
            } else if(isOperador()){
                //crea tareas propias
                return View("CrearTareaOpe", new TareaCrearView(new Tarea(), id, tableroRepo.GetAll()));
            }
            return RedirectToRoute(new { controller = "Login", action = "Index" });
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult CrearTarea(TareaCrearView tarea)
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            if(!ModelState.IsValid) { 
                tarea.MensajeDeError = "Error al crear Tarea.";
                if(isAdmin()){
                    return View("CrearTareaAdmin", tarea);
                } else {
                    return View("CrearTareaOpe", tarea);
                }
            } else {
                Tarea tareaNueva = new Tarea(tarea);
                tareaRepo.Create(tareaNueva);
                return RedirectToAction("Index");
            }
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult ModificarTarea(int id)
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            Tarea tarea = tareaRepo.GetById(id);
            if(isAdmin()){
                TareaModificarView tareaView = new TareaModificarView(tarea, usuarioRepo.GetAll());
                return View("ModificarTareaAdmin", tareaView);
            } else if(isOperador()){
                TareaModificarView tareaView = new TareaModificarView(tarea);
                return View("ModificarTareaOpe", tareaView);
            }
            return RedirectToRoute(new { controller = "Login", action = "Index" });
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult ModificarTarea(int id, TareaModificarView tareaView)
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            if(!ModelState.IsValid) { 
                tareaView.MensajeDeError = "Error al modificar Tarea.";
                if(isAdmin()){
                    return View("ModificarTareaAdmin", tareaView);
                } else {
                    return View("ModificarTareaOpe", tareaView);
                }
            } else {
                Tarea tarea = new Tarea(tareaView);
                tareaRepo.Update(id, tarea);
                return RedirectToAction("Index");
            }
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    public IActionResult EliminarTarea(int id)
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            tareaRepo.Delete(id);
            return RedirectToAction("Index");
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    
    public IActionResult Privacy()
    {
        return View();
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    private bool isLogueado()
    {
        if (HttpContext.Session != null && !string.IsNullOrEmpty(HttpContext.Session.GetString("usuario"))) 
        {
            return true;
        }                
        return false;
    }
    private bool isAdmin()
    {
        if (HttpContext.Session != null && HttpContext.Session.GetString("rol") == "Administrador") 
        {
            return true;
        }                
        return false;
    }
    private bool isOperador()
    {
        if (HttpContext.Session != null && HttpContext.Session.GetString("rol") == "Operador") 
        {
            return true;
        }                
        return false;
    }
}

Views/Tarea/CrearTareaAdmin.cshtml
@{
    ViewData["Title"] = "Crear Tarea";    
}
@using EspacioViewModels
@model TareaCrearView

@if(Model.TieneMensajeDeError)
{
    <p>@Model.MensajeDeError</p>
}
<div class="text-center d-flex flex-column align-items-center">
    <h1 class="text-dark">Crear Tarea</h1>
    <form class="w-50 my-2 p-4 border border-3 border-dark rounded-2 border-opacity-25 needs-validation" novalidate="novalidate" asp-controller="Tarea" asp-action="CrearTarea" method="post" >
        <fieldset>
            <div class="mb-3">
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Id_tablero" class="form-label text-center">Tablero</label>
                    <select asp-for="@Model.Id_tablero" class="form-select" aria-label="Default select example">
                        @foreach(var tab in Model.Tableros){
                            <option value="@tab.Id" >@tab.Nombre</option>
                        }
                    </select>
                    <span asp-validation-for="@Model.Id_tablero" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Nombre" class="form-label text-center">Nombre</label>
                    <input asp-for="@Model.Nombre" class="form-control" />
                    <span asp-validation-for="@Model.Nombre" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Descripcion" class="form-label text-center">Descripcion</label>
                    <input asp-for="@Model.Descripcion" class="form-control" />
                    <span asp-validation-for="@Model.Descripcion" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Color" class="form-label text-center">Color:</label>
                    <input type="color" class="form-control" value="#FFE9E2" name="Color" />
                    <span asp-validation-for="@Model.Color" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation" class="form-control">
                    <label asp-for="@Model.Id_usuario_asignado" class="form-label text-center">Usuario</label>
                    <select class="form-select" aria-label="Default select example" asp-for="@Model.Id_usuario_asignado">
                        @foreach(var usu in Model.Usuarios){
                            if(usu.Id == Model.Id_sesion){
                                <option value="@usu.Id" selected="selected">@usu.Nombre_de_usuario</option>
                            } else{
                                <option value="@usu.Id">@usu.Nombre_de_usuario</option>
                            }
                        }
                    </select>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Estado" class="form-label text-center">Estado</label>
                    <select class="form-select" aria-label="Default select example" asp-for="@Model.Estado">
                        <option value="0" selected>Idea</option>
                        <option value="1">Hacer</option>
                        <option value="2">Haciendo</option>
                        <option value="3">Revisar</option>
                        <option value="4">Terminada</option>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-info">Crear</button>
        </fieldset>
    </form>
</div>
@section Scripts{<partial name="_ValidationScriptsPartial"/>}

Views/Tarea/CrearTareaOpe.cshtml
@{
    ViewData["Title"] = "Crear Tarea";    
}
@using EspacioViewModels
@model TareaCrearView

@if(Model.TieneMensajeDeError)
{
    <p>@Model.MensajeDeError</p>
}
<div class="text-center d-flex flex-column align-items-center">
    <h1 class="text-dark">Crear Tarea</h1>
    <form asp-controller="Tarea" asp-action="CrearTarea" class="w-50 my-2 p-4 border border-3 border-dark rounded-2 border-opacity-25 needs-validation" novalidate="novalidate" method="post">
        <fieldset>
            <div class="mb-3">
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Id_tablero" class="form-label text-center">Tablero</label>
                    <select asp-for="@Model.Id_tablero" class="form-select" aria-label="Default select example">
                        @foreach(var tab in Model.Tableros){
                            <option value="@tab.Id" >@tab.Nombre</option>
                        }
                    </select>
                    <span asp-validation-for="@Model.Id_tablero" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Nombre" class="form-label text-center">Nombre</label>
                    <input asp-for="@Model.Nombre" class="form-control" />
                    <span asp-validation-for="@Model.Nombre" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Descripcion" class="form-label text-center">Descripcion</label>
                    <input asp-for="@Model.Descripcion" class="form-control" />
                    <span asp-validation-for="@Model.Descripcion" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Color" class="form-label text-center">Color</label>
                    <input type="color" class="form-control" value="#FFE9E2" name="Color" />
                    <span asp-validation-for="@Model.Color" class="text-danger"></span>
                </div>
        
                <input type="hidden" asp-for="@Model.Id_usuario_asignado" value="@Model.Id_sesion">

                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Estado" class="form-label text-center">Estado</label>
                    <select class="form-select" aria-label="Default select example" asp-for="@Model.Estado">
                        <option value="0" selected>Idea</option>
                        <option value="1">Hacer</option>
                        <option value="2">Haciendo</option>
                        <option value="3">Revisar</option>
                        <option value="4">Terminada</option>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-info">Crear</button>
        </fieldset>
    </form>
</div>
@section Scripts{<partial name="_ValidationScriptsPartial"/>}

Views/Tarea/Index.cshtml
@{
    ViewData["Title"] = "Tareas";    
}
@using EspacioViewModels
@model TareaListadoView

<div class="text-center">
    <h1 class="display-4">Tareas</h1>
    <table class="table caption-top table-striped table-hover">
        <thead>
            <tr class="table-dark">
                <th scope="col">Tablero</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Estado</th>
                <th scope="col">Usuario</th>
                <th scope="col">Modificar</th>
                <th scope="col">Borrar</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var tarea in Model.TareasView){
                if (tarea.Id != 0)
                {
                    <tr style="background-color: @tarea.Color;">
                        <td class="m-auto col-4">@tarea.Tablero</td>
                        <td class="m-auto">@tarea.Nombre</td>
                        <td class="m-auto">@tarea.Descripcion</td>
                        <td class="m-auto">@tarea.Estado</td>                      
                        <td class="m-auto">@tarea.Usuario</td>
                        <td>
                            @if(Model.Id_sesion == tarea.Id_usuario_asignado){
                                <a type="button" class="btn btn-outline-dark"  asp-controller="Tarea" asp-action="ModificarTarea" asp-route-id="@tarea.Id">Modificar</a>
                            }
                        </td>
                        <td>
                            @if(Model.Id_sesion == tarea.Id_usuario_asignado){ 
                                <a type="button" class="btn btn-outline-danger"  asp-controller="Tarea" asp-action="EliminarTarea" asp-route-id="@tarea.Id" onclick="return confirm('¿Estas seguro que quieres eliminar a @tarea.Nombre?')">Eliminar</a>
                            }
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a type="button" class="btn btn-outline-success" asp-area="" asp-controller="Tarea" asp-action="CrearTarea">Crear Tarea</a>
</div>

Views/Tarea/ModificarTareaAdmin.cshtml
@{
    ViewData["Title"] = "Modificar Tarea";    
}
@using EspacioViewModels
@model TareaModificarView

@if(Model.TieneMensajeDeError)
{
    <p>@Model.MensajeDeError</p>
}
<div class="text-center d-flex flex-column align-items-center">
    <h2 class="text-dark">Modificar Tarea</h2>
    <form class="w-50 my-2 p-4 border border-3 border-dark rounded-2 border-opacity-25 needs-validation" novalidate="novalidate" asp-controller="Tarea" asp-action="ModificarTarea" method="post">
        <fieldset>
            <div class="mb-3">
                <legend>Tarea: @Model.Nombre-Estado: @Model.Estado</legend>
                <input type="hidden" asp-for="@Model.Id">
                <input type="hidden" asp-for="@Model.Id_tablero">
                <input type="hidden" asp-for="@Model.Nombre">
                <input type="hidden" asp-for="@Model.Descripcion">
                <input type="hidden" asp-for="@Model.Color">
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Estado" class="form-label text-center">Estado</label>
                        <select asp-for="@Model.Estado" class="form-select" aria-label="Default select example">
                            <option value="Idea" selected>Ideas</option>
                            <option value="Hacer">Hacer</option>
                            <option value="Haciendo">Haciendo</option>
                            <option value="Revisar">Revisar</option>
                            <option value="Terminada">Terminada</option>
                        </select>
                    <span asp-validation-for="@Model.Estado" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Id_usuario_asignado" class="form-label text-center">Usuario Asignado</label>
                    <select class="form-select" aria-label="Default select example" asp-for="@Model.Id_usuario_asignado">
                        @foreach(var usu in Model.Usuarios){
                            if(usu.Id == Model.Id_usuario_asignado){
                                <option value="@usu.Id" selected="selected">@usu.Nombre_de_usuario</option>
                            } else{
                                <option value="@usu.Id">@usu.Nombre_de_usuario</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="@Model.Id_usuario_asignado" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-info">Enviar</button>
        </fieldset>
    </form>
</div>
@section Scripts{<partial name="_ValidationScriptsPartial"/>}

Views/Tarea/ModificarTareaOpe.cshtml
@{
    ViewData["Title"] = "Modificar Tarea";    
}
@using EspacioViewModels
@model TareaModificarView

@if(Model.TieneMensajeDeError)
{
    <p>@Model.MensajeDeError</p>
}

<div class="text-center d-flex flex-column align-items-center">
    <h2 class="text-dark">Modificar Tarea</h2>
    <form class="w-50 my-2 p-4 border border-3 border-dark rounded-2 border-opacity-25 needs-validation" novalidate="novalidate" asp-controller="Tarea" asp-action="ModificarTarea" method="post">
        <fieldset>
            <div class="mb-3">
                <legend>Tarea: @Model.Nombre-Estado: @Model.Estado</legend>
                <input type="hidden" asp-for="@Model.Id">
                <input type="hidden" asp-for="@Model.Id_tablero">
                <input type="hidden" asp-for="@Model.Nombre">
                <input type="hidden" asp-for="@Model.Descripcion">
                <input type="hidden" asp-for="@Model.Color">
                <input type="hidden" asp-for="@Model.Id_usuario_asignado">

                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Estado" class="form-label text-center">Estado</label>
                        <select asp-for="@Model.Estado" class="form-select" aria-label="Default select example">
                            <option value="Idea" selected>Ideas</option>
                            <option value="Hacer">Hacer</option>
                            <option value="Haciendo">Haciendo</option>
                            <option value="Revisar">Revisar</option>
                            <option value="Terminada">Terminada</option>
                        </select>
                    <span asp-validation-for="@Model.Estado" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-info">Enviar</button>
        </fieldset>
    </form>
</div>
@section Scripts{<partial name="_ValidationScriptsPartial"/>}