Models/Usuario.cs
using EspacioViewModels;
namespace EspacioModels;
public enum Roles 
{
    Operador = 0,
    Administrador = 1
}
public class Usuario{
    private int id;
    private string nombre_de_usuario;
    private string pass;
    private Roles rol;

    public int Id { get => id; set => id = value; }
    public string Nombre_de_usuario { get => nombre_de_usuario; set => nombre_de_usuario = value; }
    public string Pass { get => pass; set => pass = value; }
    public Roles Rol { get => rol; set => rol = value; }

    public Usuario(){ }

    public Usuario(UsuarioCrearView usu){
        nombre_de_usuario = usu.Nombre_de_usuario;
        pass = usu.Pass;
        rol = usu.Rol;
    }

    public Usuario(UsuarioModificarView usu){
        id = usu.Id;
        nombre_de_usuario = usu.Nombre_de_usuario;
        pass = usu.Pass;
        rol = usu.Rol;
    }
}

ViewModels/UsuarioView.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using EspacioModels;

namespace EspacioViewModels
{
    public class UsuarioView
    {
        [Display(Name = "Id")]
        public int Id {get;set;}

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Nombre de Usuario")] 
        public string Nombre_de_usuario {get;set;}        
        
        [Required(ErrorMessage = "Este campo es requerido.")]
        [PasswordPropertyText]
        [Display(Name = "Pass")]
        public string Pass {get;set;}

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Rol")]
        public Roles Rol {get;set;}

        public UsuarioView() { }

        public UsuarioView(Usuario usu)
        {
            Id = usu.Id;
            Nombre_de_usuario = usu.Nombre_de_usuario;
            Pass = usu.Pass;
            Rol = usu.Rol;
        }
    }
}

Controllers/UsuarioController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_vaninaze.Models;

using kanbanRepository;
using EspacioModels;
using EspacioViewModels;
namespace tl2_tp10_2023_vaninaze.Controllers;

public class UsuarioController : Controller
{
    private readonly ILogger<UsuarioController> _logger;
    private IUsuarioRepository usuarioRepo;
    private ITareaRepository tareaRepo;
    private ITableroRepository tableroRepo;

    public UsuarioController(ILogger<UsuarioController> logger, IUsuarioRepository _usuarioRepo, ITareaRepository _tareaRepo, ITableroRepository _tableroRepo)
    {
        _logger = logger;
        usuarioRepo = _usuarioRepo;
        tareaRepo = _tareaRepo;
        tableroRepo = _tableroRepo;
    }

    [HttpGet]
    public IActionResult Index() //Listar usuarios
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            int id = HttpContext.Session.GetInt32("id") ?? -1;
            if(isAdmin()){
                UsuarioListadoView usuarios = new UsuarioListadoView(usuarioRepo.GetAll(), id);
                return View("IndexAdmin", usuarios);
            } else if(isOperador()){
                UsuarioListadoView usuarios = new UsuarioListadoView(usuarioRepo.GetAll(), id);
                return View("IndexOpe", usuarios);
            }
            return RedirectToRoute(new { controller = "Login", action = "Index" });
        } catch (Exception ex){
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }

    [HttpGet]
    public IActionResult CrearUsuario()
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            if(isAdmin()){
                return View(new UsuarioCrearView());
            }
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult CrearUsuario(UsuarioCrearView usu)
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            if(!ModelState.IsValid) { 
                usu.MensajeDeError = "Error al crear Usuario";
                return View("CrearUsuario",usu);
            } else { 
                Usuario usuario = new Usuario(usu);
                usuarioRepo.Create(usuario);
                return RedirectToAction("Index");
            }
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult ModificarUsuario(int id)
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            if(id != 999){
                int idSesion = HttpContext.Session.GetInt32("id") ?? -1;
                if(isAdmin()){
                    Usuario usuario = usuarioRepo.GetById(id);
                    UsuarioModificarView usu = new UsuarioModificarView(usuario);
                    if(idSesion == id){
                        return View("ModificarUsuarioAdmin", usu);
                    }
                    return View("ModificarRol", usu);
                } else if(isOperador()){
                    Usuario usuario = usuarioRepo.GetById(id);
                    UsuarioModificarView usu = new UsuarioModificarView(usuario);
                    return View("ModificarUsuarioOpe", usu);
                }
            }
            return RedirectToRoute(new { controller = "Login", action = "Index" });
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult ModificarUsuario(int id, UsuarioModificarView usu)
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            if(!ModelState.IsValid) { 
                usu.MensajeDeError = "Error al modificar Usuario.";
                if(isAdmin()) {
                    return View("ModificarUsuarioAdmin", usu);
                } else {
                    return View("ModificarUsuarioOpe", usu);
                }
            } else if(id != 999){
                Usuario usuario = new Usuario(usu);
                usuarioRepo.Update(id, usuario);
            }
            return RedirectToAction("Index");
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    public IActionResult EliminarUsuario(int id)
    {
        if(!isLogueado()) {
            return RedirectToRoute(new { controller = "Login", action = "Index" }); 
        } 
        try {
            tareaRepo.DeleteByUsu(id);
            tableroRepo.DeleteByUsu(id);
            usuarioRepo.Delete(id);
            if(id == HttpContext.Session.GetInt32("id")){
                return RedirectToRoute(new { controller = "Login", action = "Logout" }); 
            }
            return RedirectToAction("Index");
        } catch (Exception ex) {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }
    
    public IActionResult Privacy()
    {
        return View();
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
    private bool isLogueado()
    {
        if (HttpContext.Session != null && !string.IsNullOrEmpty(HttpContext.Session.GetString("usuario"))) 
        {
            return true;
        }                
        return false;
    }
    private bool isAdmin()
    {
        if (HttpContext.Session != null && HttpContext.Session.GetString("rol") == "Administrador") 
        {
            return true;
        }                
        return false;
    }
    private bool isOperador()
    {
        if (HttpContext.Session != null && HttpContext.Session.GetString("rol") == "Operador") 
        {
            return true;
        }                
        return false;
    }
}

Views/Usuario/CrearUsuario.cshtml
@{
    ViewData["Title"] = "Crear Usuario";    
}
@using EspacioViewModels
@model UsuarioCrearView

@if(Model.TieneMensajeDeError)
{
    <p>@Model.MensajeDeError</p>
}
<div class="text-center d-flex flex-column align-items-center">
    <h1 class="text-dark">Crear Usuario</h1>
    <form class="w-50 my-2 p-4 border border-3 border-dark rounded-2 border-opacity-25 needs-validation" novalidate="novalidate"  asp-controller="Usuario" asp-action="CrearUsuario" method="post">
        <fieldset>
            <div class="mb-3">
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Nombre_de_usuario" class="form-label text-center">Nombre de usuario</label>
                    <input asp-for="@Model.Nombre_de_usuario" class="form-control"/>
                    <span asp-validation-for="@Model.Nombre_de_usuario" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Pass" class="form-label text-center">Contraseña</label>
                    <input asp-for="@Model.Pass" class="form-control"/>
                    <span asp-validation-for="@Model.Pass" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Rol" class="form-label text-center">Rol</label>
                    <select class="form-select" aria-label="Default select example" asp-for="@Model.Rol">
                        <option value="0" selected>Operador</option>
                        <option value="1">Administrador</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-info">Crear</button>
            </div>
        </fieldset>
    </form>
</div>
@section Scripts{<partial name="_ValidationScriptsPartial"/>}

Views/Usuario/IndexAdmin.cshtml
@{
    ViewData["Title"] = "Usuarios";    
}
@using EspacioViewModels
@model UsuarioListadoView

<div class="text-center">
    <h1 class="display-4">Lista de Usuarios</h1>
    <table class="table caption-top table-striped table-hover">
        <thead>
            <tr class="table-dark">
                <th scope="col">Nombre</th>
                <th scope="col">Rol</th>
                <th scope="col">Modificar</th>
                <th scope="col">Borrar</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var usu in Model.UsuariosView){
                if (usu.Id != 999)
                {
                    <tr>
                        <td class="m-auto" scope="row">@usu.Nombre_de_usuario</td>
                        <td class="m-auto" scope="row">@usu.Rol</td>                      
                        <td>
                            <a type="button" class="btn btn-outline-dark"  asp-controller="Usuario" asp-action="ModificarUsuario" asp-route-id="@usu.Id">Modificar</a>
                        </td>
                        <td>
                            @if(usu.Id == Model.Id_sesion)
                            {
                                <a type="button" class="btn btn-outline-danger"  asp-controller="Usuario" asp-action="EliminarUsuario" asp-route-id="@usu.Id" onclick="return confirm('¿Estas seguro que quieres eliminar a @usu.Nombre_de_usuario?')">Eliminar</a>
                            }
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a type="button" class="btn btn-outline-success" asp-area="" asp-controller="Usuario" asp-action="CrearUsuario">Crear Usuario</a>
</div>

Views/Usuario/IndexOpe.cshtml
@{
    ViewData["Title"] = "Usuarios";    
}
@using EspacioViewModels
@model UsuarioListadoView

<div class="text-center">
    <h1 class="display-4">Lista de usuarios</h1>
    <table class="table caption-top table-striped table-hover">
        <thead>
            <tr class="table-dark">
                <th scope="col">Nombre</th>
                <th scope="col">Rol</th>
                <th scope="col">Modificar</th>
                <th scope="col">Borrar</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var usu in Model.UsuariosView){
                if (usu.Id != 999)
                {
                    <tr>
                        <td class="m-auto" scope="row">@usu.Nombre_de_usuario</td>
                        <td class="m-auto" scope="row">@usu.Rol</td>
                        <td>
                            @if(Model.Id_sesion == usu.Id){
                                <a type="button" class="btn btn-outline-dark"  asp-controller="Usuario" asp-action="ModificarUsuario" asp-route-id="@usu.Id">Modificar</a>
                            }
                        </td>
                        <td>
                            @if(Model.Id_sesion == usu.Id){
                                <a type="button" class="btn btn-outline-danger"  asp-controller="Usuario" asp-action="EliminarUsuario" asp-route-id="@usu.Id" onclick="return confirm('¿Estas seguro que quieres eliminar a @usu.Nombre_de_usuario?')">Eliminar</a>
                            }
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Usuario/ModificarRol.cshtml
@{
    ViewData["Title"] = "Modificar Rol de Usuario";    
}
@using EspacioViewModels
@model UsuarioModificarView

@if(Model.TieneMensajeDeError)
{
    <p>@Model.MensajeDeError</p>
}

<div class="text-center d-flex flex-column align-items-center">
    <h2 class="text-dark">Modificar Rol de Usuario</h2>
    <form class="w-50 my-2 p-4 border border-3 border-dark rounded-2 border-opacity-25 needs-validation" novalidate="novalidate"  asp-controller="Usuario" asp-action="ModificarUsuario" method="post">
        <fieldset>
            <div class="mb-3">
                <legend>Usuario: @Model.Nombre_de_usuario</legend>
                <input type="hidden" asp-for="@Model.Id">
                <input type="hidden" asp-for="@Model.Nombre_de_usuario">
                <input type="hidden" asp-for="@Model.Pass">
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Rol" class="form-label text-center">Rol</label>
                        <select asp-for="@Model.Rol" class="form-select" aria-label="Default select example">
                            <option value="0" selected>Operador</option>
                            <option value="1">Administrador</option>
                        </select>
                    <span asp-validation-for="@Model.Rol" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-info">Enviar</button>
        </fieldset>
    </form>
</div>
@section Scripts{<partial name="_ValidationScriptsPartial"/>}

Views/Usuario/ModificarUsuarioAdmin.cshtml
@{
    ViewData["Title"] = "Modificar Usuario";    
}
@using EspacioViewModels
@model UsuarioModificarView

@if(Model.TieneMensajeDeError)
{
    <p>@Model.MensajeDeError</p>
}

<div class="text-center d-flex flex-column align-items-center">
    <h2 class="text-dark">Modificar Usuario</h2>
    <form class="w-50 my-2 p-4 border border-3 border-dark rounded-2 border-opacity-25 needs-validation" novalidate="novalidate"  asp-controller="Usuario" asp-action="ModificarUsuario" method="post">
        <fieldset>
            <div class="mb-3">
                <legend>Usuario: @Model.Nombre_de_usuario</legend>
                <input type="hidden" asp-for="@Model.Id">
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Nombre_de_usuario" class="form-label text-center">Nombre</label>
                    <input asp-for="@Model.Nombre_de_usuario" class="form-control">
                    <span asp-validation-for="@Model.Nombre_de_usuario" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Pass" class="form-label text-center">Contraseña</label>
                    <input type="password" arie-describedby="emailHelp" placeholder="Contraseña" asp-for="@Model.Pass" class="form-control">
                    <span asp-validation-for="@Model.Pass" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Rol" class="form-label text-center">Rol</label>
                        <select asp-for="@Model.Rol" class="form-select" aria-label="Default select example">
                            <option value="0" selected>Operador</option>
                            <option value="1">Administrador</option>
                        </select>
                    <span asp-validation-for="@Model.Rol" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-info">Enviar</button>
        </fieldset>
    </form>
</div>
@section Scripts{<partial name="_ValidationScriptsPartial"/>}

Views/Usuario/ModificarUsuarioOpe.cshtml
@{
    ViewData["Title"] = "Modificar Usuario";    
}
@using EspacioViewModels
@model UsuarioModificarView

@if(Model.TieneMensajeDeError)
{
    <p>@Model.MensajeDeError</p>
}

<div class="text-center d-flex flex-column align-items-center">
    <h2 class="text-dark">Modificar Usuario</h2>
    <form class="w-50 my-2 p-4 border border-3 border-dark rounded-2 border-opacity-25 needs-validation" novalidate="novalidate" asp-controller="Usuario" asp-action="ModificarUsuario" method="post">
        <fieldset>
            <div class="mb-3">
                <legend>Usuario: @Model.Nombre_de_usuario</legend>
                <input type="hidden" asp-for="@Model.Id">
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Nombre_de_usuario" class="form-label text-center">Nombre</label>
                    <input asp-for="@Model.Nombre_de_usuario" class="form-control">
                    <span asp-validation-for="@Model.Nombre_de_usuario" class="text-danger"></span>
                </div>
                <div class="mb-3 has-validation">
                    <label asp-for="@Model.Pass" class="form-label text-center">Contraseña</label>
                    <input type="password" arie-describedby="emailHelp" placeholder="Contraseña" asp-for="@Model.Pass" class="form-control">
                    <span asp-validation-for="@Model.Pass" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="@Model.Rol">
            </div>
            <button type="submit" class="btn btn-info">Enviar</button>
        </fieldset>
    </form>
</div>
@section Scripts{<partial name="_ValidationScriptsPartial"/>}